### PR TITLE
css: Adds support for size

### PR DESCRIPTION
**Pull request by dburles**
Wasn't sure if it was missing intentionally, but it seems like it should be included

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks! Originally, I was think that this API should stick to CSS properties only, but since the `[mp][xy]` shorthands are in there already, I think it makes sense to have `size` as well

**Comment by dburles** [comment]
> Thanks! Originally, I was think that this API should stick to CSS properties only, but since the `[mp][xy]` shorthands are in there already, I think it makes sense to have `size` as well

This was my exact thought too!

**Comment by dburles** [comment]
Though I do think though there is a good case that theme-ui only uses CSS properties. Especially if shorthand properties could reference theme values, then there's less need for `mpxy`, etc.

**Comment by dburles** [comment]
I really think that it's worth thinking about, especially since theme-ui isn't stable yet, a breaking change is feasible.

**Comment by dburles** [comment]
On a related note, this would mean that `variant` could no longer be accessed within the `sx` prop. 
However, perhaps that's not too much of a problem. One thing I've found is that it quickly breaks down once the variant needs to affect multiple elements at once.

So in aiming to define a consistent API across a component library, I opted instead to always provide a `variant` prop, that way I can handle both cases. The problem is then a source of confusion around having the two options available. I haven't yet found a nice, (ideally declarative) approach to handling these kinds of variants. What are your thoughts?

In the world of the `sx` prop only allowing CSS properties, the variant API could be built around the `variant` prop and also better accomodate the ability to cover multiple elements at once.

Here's an example of a basic idea:

```js
const variants = {
  primary: {
    wrapper: {
      bg: 'primary',
    },
    heading: {
      color: 'white',
    },
    subtitle: {
      color: 'textWhiteMediumEmphasis',
    },
  },
  secondary: {
    wrapper: {
      bg: 'none',
    },
    heading: {
      color: 'text',
    },
    subtitle: {
      color: 'textMediumEmphasis',
    },
  },
};

const CardHeader = ({
  title,
  subtitle,
  variant,
  ...props
}) => {
  return (
    <Flex
      {...props}
      sx={{
        borderTopLeftRadius: 'large',
        borderTopRightRadius: 'large',
        ...variants[variant].header,
      }}
    >
      <Box sx={{ flex: 1 }}>
        <Heading
          as="h6"
          sx={variants[variant].heading}
        >
          {title}
        </Heading>
        {subtitle && (
          <Text
            sx={variants[variant].subtitle}
          >
            {subtitle}
          </Text>
        )}
      </Box>
    </Flex>
  );
};

export default CardHeader;
```

**Comment by dburles** [comment]
Hey @jxnblk, just pinging you in here in case these comments got lost in the noise 🙂

**Comment by jxnblk** [comment]
Thank, I did miss this one! Mind opening a new issue with some of the thoughts here? Feel like there's some good ideas, and I don't want them to get lost

**Comment by dburles** [comment]
@jxnblk cool, I'll do that, give me a couple mins

**Comment by dburles** [comment]
@jxnblk https://github.com/system-ui/theme-ui/issues/294

**Pull request merged**
