### PR TITLE
docs(README): add @datepicker-react/styled to the "Built with Styled System" section

### PR DESCRIPTION
**Pull request by tresko**
Add @datepicker-react/styled to the "Built with Styled System" section.

### CODE REVIEW

**Comment by jxnblk** [comment]
Awesome work! Thanks!

**Comment by tresko** [comment]
Thank you. Styled System is one of the best libraries I have ever used.

**Comment by jxnblk** [comment]
Thanks! Feel free to PR that as a testimonial on the landing page 😉

**Comment by tresko** [comment]
Will do 👍

**Pull request merged**
