### PR TITLE
test(styled-system): default props order affects styles

### PR DESCRIPTION
**Pull request by angeloashmore**
Failing test related to #499.

The snapshot test has been manually altered to move `padding: 0` to the top of the list in the first test.

Note the order of the props in the tests.

## Problem

When setting default props on a component using `styled-system`, the default props may override styles defined using the style props.

```jsx
import styled from '@emotion/styled'
import { space } from 'styled-system'

const Comp = styled('div')(space)
Comp.defaultProps = { p: 0 }

// Results in Comp with no padding as if p={0} were applied after px and py.
<Comp px={2} py={1} />

// Results in Comp with padding.
<Comp p={0} px={2} py={1} />
```

If `Comp` is used with props from space, such as `px` and `py`, the generated styles will be overridden by `defaultProps.p` since `padding` takes precedence over `padding-left` and the other more-specific properties.

## Why this happens

React applies default props to the end of the props list if it has not already been defined.

```jsx
Comp.defaultProps = { p: 0 }

// Example A: Relies on defaultProps.
<Comp px={2} py={1} />
// props = { px: 2, py: 1, p: 0 }

// Example B: Does not rely on defaultProps.
<Comp p={0} px={2} py={1} />
// props = { p: 0, px: 2, py: 1 }
```

`v5` iterates over props in the order they are defined.

In Example A above, the following styles are generated:

```css
.exampleA {
  padding-left: 8px;
  padding-right: 8px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding: 0;
}
```

Where we would expect it to provide `padding: 0` at the beginning of the styles instead.

```css
.exampleB {
  padding: 0;
  padding-left: 8px;
  padding-right: 8px;
  padding-top: 4px;
  padding-bottom: 4px;
}
```

## Possible Solutions

- Iterate over configs instead of props. Slower performance and relies on order of configs rather than props (i.e. less flexible).
- Iterate over props in reverse order. Could produce unexpected style ordering.
- Recommend not using default props. Instead, compose components with default props already applied but overridable. E.g. `const Comp = props => <CompBase {...CompBase.defaultProps} {...props} />`

### CODE REVIEW

**Comment by jxnblk** [comment]
Sorry for the delay and thanks for looking into this! Not sure why this "failing" test is passing on CI. Can you confirm that it's failing locally?

**Comment by angeloashmore** [comment]
It looks like the CI checks are just for building the site on Netlify. Is there a special commit message that triggers the Jest tests on CI?

**Comment by angeloashmore** [comment]
Confirmed tests are failing on the PR:

```
FAIL packages/styled-system/test/defaultProps.js
  ● application of default props should not affect order of styles › default props not provided to instance

    expect(received).toMatchSnapshot()

    Snapshot name: `application of default props should not affect order of styles default props not provided to instance 1`

    - Snapshot
    + Received

    @@ -1,11 +1,11 @@
      .emotion-0 {
    -   padding: 0;
        padding-left: 8px;
        padding-right: 8px;
        padding-top: 4px;
        padding-bottom: 4px;
    +   padding: 0;
      }

      <div
        className="emotion-0"
        p={0}

      15 |     const props = Object.entries(tree.toJSON().props)
      16 |
    > 17 |     expect(tree).toMatchSnapshot()
         |                  ^
      18 |     expect(props).toEqual([
      19 |       ['px', 2],
      20 |       ['py', 1],

      at Object.toMatchSnapshot (packages/styled-system/test/defaultProps.js:17:18)

 › 1 snapshot failed.
```

**Comment by jxnblk** [comment]
@angeloashmore oh crap! that's my bad – looks like the tests didn't trigger at all on this PR. Let me look into it

**Comment by jxnblk** [comment]
Thanks for this, moved your commit to a new PR in #638 to continue looking into the issue!

**Comment by codeincontext** [comment]
It looks like https://github.com/styled-system/styled-system/pull/638 doesn't validate the order of the properties and this problem still exists?

Seems to be blocking us from updating to v5

**Pull request closed without merging**
