### PR TITLE
Transform width to % value in @styled-system/css

### PR DESCRIPTION
**Pull request by sebald**
Add a trnsformer for `width` so it works like `@styled-system/layout`. Meaning,

- use `theme.sizes` to interpolate values
- transform values to percentages

### CODE REVIEW

**Comment by jxnblk** [comment]
For now, this is an *intentional* omission to the `css` package's API. The thought being that it's inconsistent with the rest of the API and less likely to be familiar to people who haven't used Styled System before. That said, I'll leave this open for others to comment on

**Comment by sebald** [comment]
I see. That sounds very reasonable. I was a bit confused when using `width` the first time with `@styled-system/css` because the documentation (even though its from `styled-system`) has example for %-based responsive values 🙂

But, not supporting % values makes the API, easier to follow, because there is no difference in accessing `sizes` OR transforming it to a % value when no `sizes` are specified.

Maybe the documentation should point out that the `css` package differs from the main package and point out some differences? 🤔

**Comment by jxnblk** [comment]
Yeah, maybe having a *caveats* section would be good for now – the css packages docs are all in the readme if you want to take a stab at that

**Comment by sebald** [comment]
Will do! No promise on the time though, but soon™️.

**Comment by dapetrov** [comment]
So you don't plan to merge this for fractional width syntax working, right?

**Comment by jxnblk** [comment]
Thanks again for putting this together! I think for now we're going to close this in order to keep the css package's API a little simpler

**Pull request closed without merging**
